version: '3'

tasks:
  default:
    desc: list tasks
    cmds:
      - task --list-all --sort none

  check:
    desc: format, lint, typecheck, test
    cmds:
      - task: format
      - task: lint
      - task: typecheck
      - task: test

  format:
    desc: format
    cmds:
      - uv run ruff format

  lint:
    desc: lint
    cmds:
      - uv run ruff check

  typecheck:
    desc: typecheck
    cmds:
      - uv run ty check

  test:
    desc: run tests
    cmds:
      - uv run pytest -v
