version: '3'

tasks:
  default:
    desc: list tasks
    cmds:
      - task --list-all --sort none

  check:
    desc: format, lint, typecheck, test
    cmds:
      - task: format
      - task: lint
      - task: typecheck
      - task: test

  format:
    desc: format
    cmds:
      - uv run ruff format

  lint:
    desc: lint
    cmds:
      - uv run ruff check

  typecheck:
    desc: typecheck
    cmds:
      - uv run ty check

  test:
    desc: run tests (except E2E)
    cmds:
      - uv run pytest -v --cov=src/redi

  test:e2e:
    desc: run E2E tests
    cmds:
      - ./script/init-redmine.sh
      - uv run pytest -m e2e

  release:
    desc: release next version
    prompt: リリースしますか?
    cmds:
      - git switch develop
      - git pull
      - task: check
      - git diff --quiet # 未ステージ
      - git diff --cached --quiet # 未コミット
      - uv version --bump patch
      - git add pyproject.toml uv.lock
      - git commit -m "version $(uv version --short)"
      - git tag "$(uv version --short)"
      - git push
      - git push --tags

  demo:
    desc: generate demo
    summary: |
      vhs(https://github.com/charmbracelet/vhs)を使って デモ用のgifを生成する
      ./doc/demo.tape ->  ./doc/demo.gif
    cmds:
      - bash ./script/init-redmine-demo.sh
      - vhs ./doc/demo.tape

  rulesync:
    desc: sync skills
    cmds:
      - rulesync generate -t agentsmd,claudecode -f skills --simulate-skills
